package com.zkry.memory.domain;

public enum TripMemoryEventType {
    PLAN_CREATED, PLAN_COMPLETED, POI_ADDED, POI_REMOVED, POI_REPLACED, DAY_REORDERED,
    PACE_CHANGED, BUDGET_CHANGED, HOTEL_CHANGED, TRANSPORT_CHANGED,
    SUGGESTION_ACCEPTED, SUGGESTION_REJECTED
}
