CREATE TABLE IF NOT EXISTS trip_task (
    id BIGINT NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    owner_id BIGINT NOT NULL,
    task_type VARCHAR(40) NOT NULL,
    plan_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(128) NULL,
    status VARCHAR(32) NOT NULL,
    stage VARCHAR(64) NOT NULL,
    progress INT NOT NULL DEFAULT 0,
    progress_text VARCHAR(500) NOT NULL DEFAULT '',
    request_json LONGTEXT NOT NULL,
    result_plan_id VARCHAR(64) NULL,
    result_version INT NULL,
    result_url VARCHAR(500) NULL,
    error_code VARCHAR(80) NOT NULL DEFAULT '',
    error_message TEXT NULL,
    attempt INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 4,
    last_seq BIGINT NOT NULL DEFAULT 1,
    lock_version INT NOT NULL DEFAULT 0,
    processing_token VARCHAR(64) NULL,
    lease_until DATETIME(6) NULL,
    next_retry_at DATETIME(6) NULL,
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    create_time DATETIME(6) NOT NULL,
    update_time DATETIME(6) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trip_task_task_id (task_id),
    UNIQUE KEY uk_trip_task_idempotency (owner_id, task_type, idempotency_key),
    KEY idx_trip_task_owner_updated (owner_id, deleted, update_time),
    KEY idx_trip_task_plan_active (plan_id, task_type, status, deleted),
    KEY idx_trip_task_dispatch (status, next_retry_at, deleted),
    KEY idx_trip_task_lease (status, lease_until, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS message_outbox (
    id BIGINT NOT NULL,
    event_id VARCHAR(64) NOT NULL,
    aggregate_type VARCHAR(40) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    exchange_name VARCHAR(120) NOT NULL,
    routing_key VARCHAR(120) NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    publish_attempts INT NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(6) NOT NULL,
    claim_token VARCHAR(64) NULL,
    claim_until DATETIME(6) NULL,
    published_at DATETIME(6) NULL,
    last_error VARCHAR(1000) NOT NULL DEFAULT '',
    create_time DATETIME(6) NOT NULL,
    update_time DATETIME(6) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_message_outbox_event_id (event_id),
    KEY idx_message_outbox_publish (status, next_attempt_at, claim_until, deleted),
    KEY idx_message_outbox_aggregate (aggregate_type, aggregate_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trip_task_checkpoint (
    id BIGINT NOT NULL,
    task_id VARCHAR(64) NOT NULL,
    checkpoint_key VARCHAR(80) NOT NULL,
    payload_json LONGTEXT NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    create_time DATETIME(6) NOT NULL,
    update_time DATETIME(6) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trip_task_checkpoint (task_id, checkpoint_key),
    KEY idx_trip_task_checkpoint_task (task_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trip_plan_version (
    id BIGINT NOT NULL,
    plan_id VARCHAR(64) NOT NULL,
    version INT NOT NULL,
    created_by BIGINT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    task_id VARCHAR(64) NULL,
    result_json LONGTEXT NOT NULL,
    snapshot_json LONGTEXT NULL,
    create_time DATETIME(6) NOT NULL,
    update_time DATETIME(6) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trip_plan_version (plan_id, version),
    UNIQUE KEY uk_trip_plan_version_task (task_id),
    KEY idx_trip_plan_version_created (plan_id, deleted, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS retrieval_trace (
    id BIGINT NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    query_text TEXT NOT NULL,
    filter_json TEXT NOT NULL,
    retrieval_mode VARCHAR(40) NOT NULL,
    candidates_json LONGTEXT NOT NULL,
    final_citations_json LONGTEXT NOT NULL,
    latency_ms BIGINT NOT NULL,
    adopted TINYINT NULL,
    create_time DATETIME(6) NOT NULL,
    update_time DATETIME(6) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_retrieval_trace_id (trace_id),
    KEY idx_retrieval_trace_created (deleted, create_time),
    KEY idx_retrieval_trace_adopted (adopted, deleted, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
